-- Your SQL goes here

CREATE TABLE overview(
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "lat" TEXT,
    "lon" TEXT,
    "title" TEXT,
    "context" TEXT,
    "created" TIMESTAMP NOT NULL    

);